- pkg/file/ftp.go
- pkg/file/ftp_test.go
- pkg/file/retryFileStore_test.go
**Previosuly,** Test_Move fails intermittently due to lot of ftp connections it is making.
**Currently,** We are closing connection at end after operation has been completed in Test_move such that we will not get connection related errors.
closes #15
> Fix Test_move in ftp

- .github/setups/setup.sql
- .github/workflows/go.yml
- examples/universal-example/main_test.go
- examples/using-awssns/Readme.md
- examples/using-awssns/configs/.test.env
- examples/using-awssns/init.sh
- examples/using-awssns/main_test.go
- examples/using-eventhub/main_test.go
- examples/using-mysql/configs/.env
- examples/using-mysql/configs/.test.env
- examples/using-mysql/main_test.go
- pkg/datastore/db_test.go
- pkg/datastore/pubsub/eventhub/eventhub_test.go
- pkg/file/ftp_test.go
- pkg/gofr/new_test.go
- pkg/gofr/retryDBConnection_test.go
- pkg/log/levelService_test.go
- Remove `t.Skip()` from tests wherever needed.
- Refactor the schema of setup.sql to be loaded before testing examples.
- Remove build integration tag from tests files used to skip them in workflow.
> Remove t.skip() from tests

- pkg/middleware/cors.go
- pkg/middleware/cors_test.go
- Resolves Issue #138 
- Origin Header will not be propagated from one microservice to another during interservice calls
> remove Origin from the list of necessary CORS header

- pkg/file/azure.go
- pkg/file/azure_test.go
1. Add function to check uint16 limit
> Add check for uint16 bounds in Azure Filestore

- examples/http-server/main.go
- pkg/gofr/logging/logger.go
- pkg/gofr/service/new.go
- pkg/gofr/service/new_test.go
Success :
Internal Server Errors : 
Bad request and 4xx errors:
> Add Service request log format for success responses and errors

- pkg/gofr/container/container.go
- pkg/gofr/gofr.go
- pkg/gofr/gofr_test.go
- pkg/gofr/logging/logger.go
- pkg/gofr/logging/logger_test.go
Running a cmd application, logs are getting printed as running an HTTP application, which is not expected of a CMD app
Added a new file logging function to print the logs to a file using `CMD_LOGS_FILE` env, and if the file name is not present the logs are sent to io.Discard, so they are not printed on the terminal.
Also segregated the initialization of data sources to Create() so that we can change a container's features (ex. Logger).
> fix CMD application unnecessary logs

- docs/advanced-guide/publishing-custom-metrics/page.md
- docs/quick-start/observability/page.md
- examples/using-custom-metrics/main.go
- pkg/gofr/container/container.go
- pkg/gofr/datasource/redis/hook.go
- pkg/gofr/datasource/sql/db.go
- pkg/gofr/grpc/log.go
- pkg/gofr/http/middleware/logger.go
- pkg/gofr/service/new.go
- Convert `microseconds` to `milliseconds` in logs
> Improve Logs

- pkg/gofr/config/godotenv.go
-   Moved `defaultFileName` and `defaultOverrideFileName` to const block
-  Refactored the logic to not throw an error for .local.env unless specified in `APP_ENV`
Closes #416
> Remove error for .local.env

- examples/http-server-using-redis/main_test.go
- examples/using-add-rest-handlers/main_test.go
- examples/using-file-bind/main_test.go
- examples/using-migrations/main_test.go
- examples/using-publisher/main_test.go
- pkg/gofr/crud_handlers_test.go
- pkg/gofr/handler.go
- pkg/gofr/handler_test.go
- pkg/gofr/http/responder.go
- pkg/gofr/http/responder_test.go
- Added types `PostResponder` and `DeleteResponder` implementing Responder interface to write responses for post and delete requests respectively
- Updated `ServeHTTP` method to create instances of `Responder` on the basis of request methods
- For details refer https://github.com/gofr-dev/gofr/issues/446
> Fix status code for response of Post and Delete requests

- go.mod
- pkg/gofr/container/container.go
- #410 updated the duration unit from microseconds to milliseconds but the metrics buckets weren't updated. Fixed the issue and updated buckets accordingly.
**Checklist:**
> Fix metrics buckets

- pkg/gofr/datasource/sql/metrics.go
- pkg/gofr/datasource/sql/mock_metrics.go
- pkg/gofr/http/metrics.go
- pkg/gofr/http/middleware/metrics.go
- pkg/gofr/http/middleware/metrics_test.go
- pkg/gofr/metrics/register.go
- pkg/gofr/metrics/store.go
- Currently, labels support is not there for gauge metrics due to usage of [asynchronous](https://pkg.go.dev/go.opentelemetry.io/otel/metric@v1.24.0#Float64ObservableGauge) type metric.
- Added a custom type `float64Gauge` and implemented the required methods i.e `callbackFunc` and `set` on the custom type so that we can add the support of labels.
Closes: #489
**Checklist:**
> Add support for labels in gauge metrics

- pkg/gofr/crud_handlers.go
- pkg/gofr/crud_handlers_test.go
- pkg/gofr/datasource/sql/bind.go
- pkg/gofr/datasource/sql/bind_test.go
- pkg/gofr/datasource/sql/sql_mock.go
- pkg/gofr/datasource/sql/sql_test.go
-   Fixed [issue #535](https://github.com/gofr-dev/gofr/issues/535).
-   Introduced new exported method `sql.Rebind`, used to replace **bindvars** according to dialect provided.
**Checklist:**
> Fix PostgreSQL support in AddRESTHandlers.

- docs/advanced-guide/middlewares/page.md
- docs/navigation.js
- pkg/gofr/gofr.go
- pkg/gofr/gofr_test.go
- pkg/gofr/http/router.go
- pkg/gofr/httpServer.go
- Added a exported method `app.UseMiddleware()` that allows user to add their custom middleware.
- Closes issue #493 
```go
package main
import (
"fmt"
"net/http"
"gofr.dev/pkg/gofr"
"gofr.dev/pkg/gofr/logging"
)
func main() {
// Create a new application
a := gofr.New()
a.UseMiddleware(customMiddleware(a.Logger()))
a.GET("/hello", HelloHandler)
a.Run()
}
func HelloHandler(c *gofr.Context) (interface{}, error) {
name := c.Param("name")
if name == "" {
c.Log("Name came empty")
name = "World"
}
return fmt.Sprintf("Hello %s!", name), nil
}
func customMiddleware(logger logging.Logger) func(inner http.Handler) http.Handler {
return func(inner http.Handler) http.Handler {
return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
logger.Infof("hi! from custom …
```
> allow adding custom middleware

- .github/workflows/go.yml
- .golangci.yml
- pkg/gofr/container/health_test.go
- pkg/gofr/datasource/pubsub/google/google.go
- pkg/gofr/datasource/pubsub/mqtt/mqtt_test.go
- pkg/gofr/datasource/redis/redis_test.go
- pkg/gofr/datasource/sql/db_test.go
- pkg/gofr/exporter_test.go
- pkg/gofr/gofr_test.go
- pkg/gofr/grpc/log_test.go
- pkg/gofr/handler_test.go
- pkg/gofr/http/middleware/apikey_auth_test.go
- pkg/gofr/http/middleware/basic_auth_test.go
- pkg/gofr/http/middleware/logger.go
- pkg/gofr/http/middleware/metrics_test.go
- pkg/gofr/http/middleware/oauth_test.go
- pkg/gofr/http/middleware/tracer.go
- pkg/gofr/http/router_test.go
- pkg/gofr/httpServer_test.go
- pkg/gofr/logging/dynamicLevelLogger_test.go
- pkg/gofr/service/apikey_auth_test.go
- pkg/gofr/service/basic_auth_test.go
- pkg/gofr/service/circuit_breaker_test.go
- pkg/gofr/service/oauth_test.go
- pkg/gofr/subscriber_test.go
- Update **golangci-lint** version from **v1.55.2** to **v1.57.2**
- Remove all deprecated linter flags 
- WARN [config_reader] The configuration option `linters.govet.check-shadowing` is deprecated. enable `shadow` instead.
- WARN [config_reader] The configuration option `linters.gci.local-prefixes` is deprecated, using `prefix()` inside `linters.gci.sections`. 
- WARN [config_reader] The configuration option `linters.gomnd.settings` is deprecated. using the options `linters.gomnd.checks`,`linters.gomnd.ignored-numbers`,`linters.gomnd.ignored-files`,`linters.gomnd.ignored-functions`. 
**Checklist:**
-   [x] I …
> [EN]: Update golangci-lint to Version v1.57.2

- pkg/gofr/datasource/pubsub/kafka/kafka.go
- pkg/gofr/datasource/pubsub/kafka/kafka_test.go
> Add context to subscribed KAFKA message

- pkg/gofr/service/logger.go
- pkg/gofr/service/logger_test.go
- Fixed logs format for http service calls
**Before:**
**After:**
**Checklist:**
> Fix formatting for service call logs

- examples/using-migrations/readme.md
added docker command in examples/using-migrations/readme.md to run kafka 
close https://github.com/gofr-dev/gofr/issues/619
> updated readme file for exmaples/using-migrations to run kafka

- pkg/gofr/service/apikey_auth.go
- pkg/gofr/service/basic_auth.go
- pkg/gofr/service/basic_auth_test.go
- pkg/gofr/service/circuit_breaker.go
- The structs were exported unnecessarily, and are not to be used outside the package. Hence, made them unexported.
**Checklist:**
> [FIX] Unexport service package structs

- pkg/gofr/http/errors.go
- pkg/gofr/http/errors_test.go
-   Adds a new error `ErrorEntityAlreadyExists` to http errors.
**Checklist:**
> add entity already exists error

- examples/http-server/main.go
- pkg/gofr/context.go
-   Use `defer` to close span in `http-server` example **/trace** endpoint to avoid unwanted spans behaviour.
- Add `TODO` for further work needed to permanently fix the incomplete redis spans. 
> use defer to close span and add TODO

- docs/references/configs/page.md
- pkg/gofr/gofr.go
- pkg/gofr/handler.go
Removed default value of 5 sec for REQUEST_TIMEOUT. Now, it will be configured only when user specifies this in the env configs.
Closes: #698
> Revert request_timeout default value

- pkg/gofr/handler.go
- pkg/gofr/handler_test.go
- pkg/gofr/http/errors.go
- pkg/gofr/http/errors_test.go
Error for request timeout was coming in text format instead of json body. Created a new error type `ErrorRequestTimeout` to fix this.
**Before**:
```text
Request timed out
```
**Now**:
```json
{
"error": {
"message": "request timed out"
}
}
```
> Create error for request timeout

- docs/advanced-guide/http-authentication/page.md
- pkg/gofr/gofr.go
- pkg/gofr/gofr_test.go
- pkg/gofr/http/middleware/apikey_auth.go
- pkg/gofr/http/middleware/apikey_auth_test.go
- pkg/gofr/http/middleware/basic_auth.go
- pkg/gofr/http/middleware/basic_auth_test.go
- pkg/gofr/http/middleware/oauth_test.go
-  Resolves issue #728 
-  Change the **validator func signature** in `basic auth` and `api key auth` middleware.
-   Earlier the validator func signature for **BasicAuthMiddleware** used to be :
```go
func(username, password string) bool {}
```
Updated to:
```go
func(c *container.Container, username, password string) bool {}
```
Similar change for **ApiKeyAuthMiddleware's** validator func signature
**Checklist:**
> add container in auth middleware

- .github/workflows/website_prod.yml
> Refactor deploy and dockerize only on tag release

- examples/using-cron-jobs/go.mod
- examples/using-cron-jobs/go.sum
- examples/using-web-socket/go.mod
- examples/using-web-socket/go.sum
- Running `go mod tidy` updates the files for the `using-cron` and `using-websocket` examples.
> Fixed go.mod for examples

- pkg/gofr/gofr.go
- pkg/gofr/httpServer.go
- pkg/gofr/httpServer_test.go
-   Closes issue #772 
- The profilling endpoints will be automatically enabled when the `APP_ENV` is set to `DEBUG`
**Checklist:**
> Add support for profilling endpoints.

- docs/references/configs/page.md
- pkg/gofr/gofr.go
- pkg/gofr/gofr_test.go
- Provided support for custom tracer URL, using the config `TRACER_URL`
- Deprecated `TRACER_HOST` and `TRACER_PORT`
**Checklist:**
> Support custom tracer url

- pkg/gofr/logging/logger.go
- Fatal log methods were mistakenly removed in #801, which caused a breaking change.. Hence, added them back
- Closes: #841
> Revert removing of fatal logs

- pkg/gofr/config/godotenv.go
- pkg/gofr/config/godotenv_test.go
- Fail app start in case of any error in `.env` or `.<APP_ENV>.env` files.
- Closes: #852
**Checklist:**
> Fail app if error in config files

- docs/quick-start/observability/page.md
- examples/using-add-rest-handlers/configs/.env
- examples/using-migrations/configs/.env
- pkg/gofr/gofr.go
- pkg/gofr/gofr_test.go
- Add checks for missing tracer configs
- Remove usage of TRACER_HOST, TRACER_PORT as these were deprecated
- Closes: #851
**Checklist:**
> Fix tracer config validation

- pkg/gofr/http_server.go
- pkg/gofr/metrics_server.go
- For forceful shutdown, these error logs were coming up everytime:
- The error was coming from ListenAndServe method when the server is shutting down.
**Checklist:**
> Fix error logs for shutdown

- pkg/gofr/container/container_test.go
- pkg/gofr/datasource/pubsub/mqtt/mqtt.go
Closes #790 
- Used mock Pubsub for container tests as an actual connection to MQTT was not required
- Changed the public broker from HiveMQ to EQMX for more stable connections
> Fix intermittent fail for container and MQTT tests

- pkg/gofr/gofr.go
- pkg/gofr/gofr_test.go
- pkg/gofr/migration/migration.go
- pkg/gofr/migration/migration_test.go
- pkg/gofr/version/version.go
- Resolved DB migrations panic in logging
App was panicking while logging with migrations datasource, as the logger was `nil`. Now, populated the logger, hence fixing the panic.
- Removed unnecessary error log for tracing
`{"level":"ERROR","time":"2024-08-06T17:47:56.714963+05:30","message":"unsupported TRACE_EXPORTER: ","gofrVersion":"v1.16.0"}`
The above log was coming out even even tracing configs (TRACE_EXPORTER, TRACER_URL) weren't provided, and since tracing is optional feature, removed error log if configs aren't given.
> Release v1.16.1

- pkg/gofr/cmd/request.go
- Reduce Request.Bind cognitive complexity to 12
- Closes #998 
- Previously the reflect.Struct check was nested, increasing the Cognitive Complexity to 16. Refactoring the code to check this beforehand makes the Cognitive Complexity 12
- Functionality is kept same
**Checklist:**
> refactor: reduce cognitive complexity

- pkg/gofr/container/container.go
- pkg/gofr/container/mock_datasources.go
- pkg/gofr/container/mock_metrics.go
- Updates incorrect overview for container package
- [issue](https://github.com/gofr-dev/gofr/issues/991)
**Checklist:**
> doc: Update container package overview

- pkg/gofr/container/container_test.go
- pkg/gofr/datasource/redis/redis.go
- pkg/gofr/datasource/redis/redis_test.go
Fixes [#1078](https://github.com/gofr-dev/gofr/issues/1078)
Handled the panic when calling redis ping function when the connection is not available.
> fixes: [issue 1078] handled panic in redis ping

- README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [GoFr Guru](https://gurubase.io/g/gofr) to Gurubase. GoFr Guru uses the data from this repo and data from the [docs](https://gofr.dev/) to answer questions by leveraging the LLM.
In this PR, I showcased the "GoFr Guru", which highlights that GoFr now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable GoFr Guru …
> Introducing GoFr Guru on Gurubase.io

- pkg/gofr/datasource/pubsub/google/google.go
- pkg/gofr/datasource/pubsub/google/google_test.go
- pkg/gofr/version/version.go
The callback function for the Google client Subscribe function was configured to fetch one message per Subscribe call. Still, at times the message was being sent to a closed channel causing unexpected behaviour. Fixed the issue of receiving messages on a channel that closes only on application shutdown.
> Release v1.27.1

- docs/advanced-guide/gofr-errors/page.md
- pkg/gofr/handler.go
- pkg/gofr/handler_test.go
- pkg/gofr/http/errors.go
- pkg/gofr/logging/logger.go
This PR is an alternative implementation of what was initiated with
- #1295
- #1298 
It goes further than #1298 as it allows defining the log level for any error, not only the HTTP errors
It also provides a way for user to provide a log level for their custom errors (See [docs/advanced-guide/gofr-errors/page.md](https://github.com/gofr-dev/gofr/blob/development/docs/advanced-guide/gofr-errors/page.md))
Fixes #1279
Replaces #1295
Replaces #1298
**Checklist:**
-   [X] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [X] All new code is covered by unit tests.
-   [X] This PR does not decrease the overall code coverage.
-   [X] I have reviewed the code comments and documentation for clarity.
> Decrease log level for 4xx HTTP errors : alternative option

- pkg/gofr/datasource/pubsub/mqtt/mqtt.go
-   Change the public broker used for default MQTT connection in tests.
> change mqtt broker to eclipse broker

- .golangci.yml
- **ci: remove deprecated linters from golangci**
- **ci: exportloopref was renamed to copyloopvar**
> golangci: remove deprecated linters

- .golangci.yml
- pkg/gofr/context_test.go
- pkg/gofr/datasource/solr/solr.go
- pkg/gofr/gofr_test.go
- pkg/gofr/http/middleware/apikey_auth.go
- pkg/gofr/http/middleware/apikey_auth_test.go
- pkg/gofr/http/request.go
- pkg/gofr/http/request_test.go
- pkg/gofr/service/new_test.go
- **ci: enable canonicalheader in golangci-lint**
- **chore: use canonical form for all HTTP headers**
> enable canonicalheader linter in golangci-lint

- pkg/gofr/datasource/pubsub/kafka/interfaces.go
- pkg/gofr/datasource/pubsub/kafka/kafka.go
- pkg/gofr/datasource/pubsub/kafka/kafka_test.go
- pkg/gofr/datasource/pubsub/kafka/mock_interfaces.go
When calling kafka-go ReadMessage, it include commit message behavior for line
`pkg/gofr/datasource/pubsub/kafka/kafka.go:168`. After method done, Committer.Commit is not useful.
It should fetch first then commit later.
Below is kafka-go source code
```go
func (r *Reader) ReadMessage(ctx context.Context) (Message, error) {
m, err := r.FetchMessage(ctx)
if err != nil {
return Message{}, fmt.Errorf("fetching message: %w", err)
}
if r.useConsumerGroup() {
if err := r.CommitMessages(ctx, m); err != nil {
return Message{}, fmt.Errorf("committing message: %w", err)
}
}
return m, nil
}
```
**Checklist:**
-   [v] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [v] All new code is covered by unit tests.
-   [v] This PR does not …
> subscribe kafka shouldn't commit before handler execute

- docs/advanced-guide/grpc/page.md
- examples/grpc/grpc-client/client/hello_client.go
- examples/grpc/grpc-client/main.go
-   We now pass app.Metrics() instead of app, while registering the metrics for our gRPC clients.
**Checklist:**
> Fix: Propagation of metrics to create gRPC Client

- docs/advanced-guide/overriding-default/page.md
- examples/using-html-template/main.go
- examples/using-html-template/static/index.html
- examples/using-html-template/static/style.css
- examples/using-html-template/templates/todo.html
- pkg/gofr/http/responder.go
- pkg/gofr/http/responder_test.go
- pkg/gofr/http/response/template.go
A new type response.Template is introduced. It takes a name of the template and the data. Based on the name template is being read from "templates" folder by default and we are using the data to render the said template. 
fixes #1515 for now. Eventually we may want to make the folder name customisable or add more header support. For now, current issue gets fixed while ensuring that other people who are not concerned about template do not get affected.
> Adding HTML template support.

- CONTRIBUTING.md
- Added a note to the Contribution Guidelines stating that the project follows American English spelling conventions (e.g., "favor" vs. "favour")
- Fixes #1667
> document use of American English in CONTRIBUTING.md

- .github/workflows/go.yml
- .golangci.yml
- examples/grpc/grpc-streaming-server/main_test.go
- examples/grpc/grpc-streaming-server/server/chatservice_server.go
- examples/grpc/grpc-unary-server/server/hello_server.go
- examples/using-add-filestore/main_test.go
- examples/using-cron-jobs/main_test.go
- pkg/gofr/cmd/terminal/spinner_test.go
- pkg/gofr/cmd_test.go
- pkg/gofr/cron_test.go
- pkg/gofr/datasource/arangodb/arango_document_test.go
- pkg/gofr/datasource/file/fs_test.go
- pkg/gofr/datasource/sql/db_test.go
- pkg/gofr/http/request_test.go
- pkg/gofr/logging/logger_test.go
- pkg/gofr/service/response_test.go
- **Use golangci-lint migration tool**
- **Restore the comments stripped by golangci-lint migration tool**
- **Remove useless exclusions from golangci-lint**
- **Remove legacy "lax" option from golangci-lint config**
- **Add TODO comments for golangci-lint presets**
- **Remove some staticcheck rules from golangci-lint config**
- **Fix behavior of golangci-lint against Go comments**
- **Apply suggested fixes provided by latest golangci-lint version**
- **Fix errors reported by testifylint**
- **Apply suggested fixes provided by latest golangci-lint version**
- **Migrate GitHub Actions to use golangci-lint v2**
Fixes #1645
- None
- developers are now supposed to use golangci-lint v2
- 
**Checklist:**
-   [X] …
> Migrate to golangci-lint v2

- pkg/gofr/config/godotenv.go
- pkg/gofr/config/godotenv_test.go
- Currently, we are using Overload for overriding. This causes the system environment variables to be overwritten. To handle this, we now run a manual loop that skips all environment variables initially loaded from the system.
> Fix config Overloading & its tests
