- .github/workflows/go.yml
> remove if always true condition from code climate step

- examples/using-solr/handler/handler_test.go
- pkg/service/http_test.go
> resovle govet warnings

- pkg/constants.go
- pkg/datastore/pubsub/eventbridge/eventbridge.go
- pkg/datastore/pubsub/eventhub/eventhub.go
- pkg/datastore/pubsub/kafka/kafka.go
- pkg/datastore/pubsub/metrics.go
- Removed duplicate metrics from the pubsub package and added those in the common file(metrics.go).
Github issue: https://github.com/gofr-dev/gofr/issues/89
> Removed duplicate metrics and added in the common file

- examples/http-server/main.go
- pkg/gofr/context.go
- pkg/gofr/http/middleware/tracer.go
- pkg/gofr/service/new.go
> Fix the trace tree and add feature for inter service trace propagation

- .github/workflows/docs.yml
- docs/Dockerfile
- docs/navigation.js
- docs/page.md
- docs/quick-start/connecting-mysql/page.md
- docs/quick-start/connecting-redis/page.md
- docs/quick-start/introduction/page.md
1. Deployment is done on staging.gofr.dev when PR is merged to development or main with changes in docs directory.
2. Deployment is done on gofr.dev when tag is released with changes in docs directory.
3. Stage image is deployed to prod with retagging feature.
4. Dockerize stage will fail if the docs are not properly formatted based on checks done by UI.
> Docs Release Setup

- pkg/gofr/metrics/register_test.go
Add tests for new metric initialisation error
> Increase metrics test coverage

- examples/using-file-bind/README.md
> add README.md for using-file-bind example

- pkg/gofr/http/middleware/basic_auth.go
- pkg/gofr/http/middleware/basic_auth_test.go
- Resolves #461 
- Reference :  https://datatracker.ietf.org/doc/html/rfc7617 
**Checklist:**
> change keyword basic to Basic while checking auth header

- .github/workflows/website.yml
> remove extra bracket in image

- .codeclimate.yml
- Added `.codeclimate.yml` file to define custom checks and respective thresholds.
Closes: #483
**Checklist:**
> Add code-climate yaml file

- .codeclimate.yml
- #478 specified the method-complexity to 20, which is not ideal. Hence, updated it to 12.
**Checklist:**
> FIx .codeclimate.yml

- pkg/gofr/datasource/sql/sql.go
- pkg/gofr/datasource/sql/sql_mock.go
- pkg/gofr/datasource/sql/sql_test.go
> Refactor SQL Mock and add test

- README.md
Adds discord join link as a badge. [discord](https://discord.gg/wsaSkQTdgq)
**Checklist:**
> Add discord join badge

- pkg/gofr/migration/migration_test.go
- pkg/gofr/migration/pubsub_test.go
> Increase Migration test coverage

- docs/quick-start/configuration/page.md
Fix configurations path in GoFr project directory structure
> Fix configurations path

- .github/workflows/website.yml
- docs/quick-start/add-rest-handlers/page.md
> change trigger for website.yaml

- pkg/gofr/datasource/README.md
> Add readme for datasource

- docs/advanced-guide/overriding-default/page.md
- pkg/gofr/handler.go
- pkg/gofr/handler_test.go
- Closes issue #474 
**Checklist:**
> Add support for custom favicon.ico

- .github/workflows/go.yml
- CONTRIBUTING.md
- examples/using-publisher/readme.md
- examples/using-subscriber/readme.md
- fix failing `example testing` step in github workflow due to old image 
**Checklist:**
> test workflow with new image

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
> add issue template for bug, feature and questiosn

- examples/using-migrations/readme.md
- pkg/gofr/datasource/pubsub/kafka/kafka.go
- Kafka connection log was having `extra comma` at the end, removed that.
- Updated `using-migrations` readme to have Kafka docker command. (Done in #622)
**Checklist:**
> Fix Kafka log

- docs/references/configs/page.md
> change table format in config documentation

- pkg/gofr/externalDB.go
> Mark use mongo deprecated

- pkg/gofr/http/middleware/oauth.go
- pkg/gofr/http/middleware/oauth_test.go
> FIX Oauth Making request repeatedly bypassing refresh interval 

- docs/quick-start/add-rest-handlers/page.md
- pkg/gofr/crud_handlers.go
- pkg/gofr/crud_handlers_test.go
- pkg/gofr/gofr.go
- pkg/gofr/http/middleware/oauth.go
- pkg/gofr/http/middleware/oauth_test.go
- pkg/gofr/version/version.go
- Added support to set table name and rest path in REST handlers. (#648)
- Fixed OAuth call before refresh interval in case of error. (#665)
> Release v1.8.0

- pkg/gofr/crud_handlers_test.go
- pkg/gofr/datasource/sql/db.go
- pkg/gofr/datasource/sql/db_test.go
> Add missing QueryContext method in sql

- examples/http-server/main.go
- examples/http-server/main_test.go
> fix response in trace handler

- pkg/gofr/logging/logger.go
- pkg/gofr/logging/logger_test.go
> fix: terminal pretty printing logs misaligned 

- .github/workflows/changes.sh
- .github/workflows/website.yml
- docs/quick-start/observability/page.md
Reverts gofr-dev/gofr#693
Pipeline is failing for external contributors
> Revert "Update workflow and docs for docs deployment"

- docs/advanced-guide/middlewares/page.md
- fixes issue #721 
**Checklist:**
> Improve usage for gofr/http/Middleware in documentation

- pkg/gofr/migration/migration.go
- pkg/gofr/migration/redis.go
- pkg/gofr/migration/sql.go
I have added some debug logs for migrations.
If I missed on some of the logs do let me know, I'll add them.
Fixes #477 
**Checklist:**
> add debug logs for migrations

- pkg/gofr/http/middleware/oauth_test.go
> Update oauth expired token

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
- docs/advanced-guide/grpc/page.md
- docs/advanced-guide/handling-data-migrations/page.md
- docs/advanced-guide/overriding-default/page.md
- docs/advanced-guide/publishing-custom-metrics/page.md
- docs/advanced-guide/swagger-documentation/page.md
- docs/advanced-guide/using-cron/page.md
- docs/page.md
- docs/quick-start/add-rest-handlers/page.md
- docs/quick-start/configuration/page.md
- docs/quick-start/introduction/page.md
- docs/quick-start/observability/page.md
- examples/using-cron-jobs/main.go
- examples/using-file-bind/README.md
- examples/using-file-bind/main.go
- pkg/gofr/cron_test.go
- pkg/gofr/datasource/README.md
- pkg/gofr/datasource/mongo/logger.go
- pkg/gofr/datasource/mongo/mock_logger.go
- pkg/gofr/datasource/redis/hook_test.go
- pkg/gofr/datasource/sql/sql_test.go
- **chore: fix typos and style**
- **chore: improve style**
> typos suggestion

- docs/advanced-guide/publishing-custom-metrics/page.md
- Added `labels` explanation and usage in custom metrics
- Fixed method name in `UpDownCounter` usage.
- Closes: #748
> Enhance custom metrics doc

- .golangci.yml
- examples/grpc-server/grpc/hello.pb.go
- examples/grpc-server/grpc/hello_grpc.pb.go
- examples/using-file-bind/main_test.go
- examples/using-migrations/main.go
- examples/using-migrations/migrations/1708322067_create_employee_table_test.go
- examples/using-migrations/migrations/1708322089_redis_add_employee_name.go
- examples/using-migrations/migrations/1708322089_redis_add_employee_name_test.go
- examples/using-publisher/main.go
- pkg/gofr/container/container.go
- pkg/gofr/container/mock_datasources.go
- pkg/gofr/datasource/clickhouse/clickhouse_test.go
- pkg/gofr/datasource/mongo/mongo_test.go
- pkg/gofr/datasource/pubsub/google/health.go
- pkg/gofr/datasource/pubsub/mqtt/mock_interfaces.go
- pkg/gofr/datasource/redis/hook.go
- pkg/gofr/datasource/redis/redis_test.go
- pkg/gofr/exporter.go
- pkg/gofr/grpc.go
- pkg/gofr/http/middleware/basic_auth_test.go
- pkg/gofr/http/middleware/metrics_test.go
- pkg/gofr/http/middleware/web_socket.go
- pkg/gofr/http/middleware/web_socket_test.go
- pkg/gofr/logging/remotelogger/dynamicLevelLogger_test.go
- pkg/gofr/migration/interface.go
- pkg/gofr/migration/mock_interface.go
- pkg/gofr/service/circuit_breaker_test.go
- pkg/gofr/service/retry_test.go
- pkg/gofr/websocket/websocket_test.go
> ci: enable recent gci linter options and fix reported errors

- docs/advanced-guide/gofr-errors/page.md
- examples/http-server/main_test.go
- pkg/gofr/handler_test.go
- pkg/gofr/http/errors.go
- pkg/gofr/http/errors_test.go
- pkg/gofr/http/responder.go
- pkg/gofr/http/responder_test.go
Reverts gofr-dev/gofr#797 as this is a breaking change, and should be included in `v2.0.0`
> Revert "Enhance errors with multiple and custom errors"

- pkg/gofr/logging/logger_test.go
- Added test for fatal log method (os.Exit issue)
- Fixed validations for warn log tests
- Closes: #844
**Checklist:**
> Fix logger tests

- README.md
-   Change port from 8080 to 8000
> Fix :: change port from 8080 to 8000

- pkg/gofr/gofr.go
- pkg/gofr/gofr_test.go
> Fix otlp exporter

- docs/references/context/page.md
-   Remove typo in docs.
**Checklist:**
> remove typo in docs

- pkg/gofr/gofr.go
- pkg/gofr/http/middleware/basic_auth.go
- pkg/gofr/http/middleware/basic_auth_test.go
-   Resolves issue #918 
-   Resolves issue #917 
**Checklist:**
> fix panic and logic for validition in basic auth

- pkg/gofr/context_test.go
Adding test functions for context.go file
- Goal is to increase overall coverage of the gofr package.
- I have added test for functions, not covered before in context.go file.
**Checklist:**
> Tests for context.go file

- docs/references/context/page.md
> fix context docs

- pkg/gofr/container/mock_container.go
- Add `MockMetrics` in the Mocks returned by NewMockContainer used for testing
**Checklist:**
> insert mock metrics in mocks returned by NewMockContainer

- pkg/gofr/datasource/clickhouse/clickhouse.go
- pkg/gofr/datasource/clickhouse/go.mod
> Fix Clickhouse go.mod

- pkg/gofr/gofr.go
-   fixes issue mentioned in comment [[comment]](https://github.com/gofr-dev/gofr/issues/1058#issuecomment-2391000070)
-   #1058 
**Checklist:**
> Initialising Tracing irrespective of configs

- pkg/gofr/datasource/pubsub/eventhub/go.mod
> Update module name for eventhub

- docs/advanced-guide/dealing-with-sql/page.md
- fix a typo in the SQLite section where PostgreSQL was mentioned
> typo: advanced-guide/dealing-with-sql

- pkg/gofr/datasource/cassandra/cassandra.go
- pkg/gofr/datasource/cassandra/cassandra_batch.go
- pkg/gofr/datasource/cassandra/logger.go
-   closes #1100 
-   Previous :
-   Now :
**Checklist:**
> Correcting cassandra migration logs

- README.md
-  The style of the GOFR GURU badge was incorrect.
**Checklist:**
> fixed gofr guru badge design

- docs/advanced-guide/injecting-databases-drivers/page.md
- docs/advanced-guide/key-value-store/page.md
-   Resolve issue #1180 
**Checklist:**
> add go get commands for all external databases

- pkg/gofr/gofr.go
- pkg/gofr/gofr_test.go
- pkg/gofr/subscriber.go
-   Fix issue #1257 .
**Checklist:**
> add empty topic and handleFunc check in Subscribe method

- pkg/gofr/datasource/cassandra/cassandra.go
- pkg/gofr/datasource/cassandra/cassandra_batch.go
- pkg/gofr/datasource/cassandra/cassandra_batch_test.go
- pkg/gofr/datasource/cassandra/cassandra_test.go
-   prequisite to closing #964 
-  this PR has been made to separate concerns of different datasources in different PRs.
**Checklist:**
> fixing linters and test in cassandra datasources

- pkg/gofr/datasource/clickhouse/clickhouse.go
- pkg/gofr/datasource/clickhouse/clickhouse_test.go
-   prerequisite to closing #964 
**Checklist:**
> fixing linters and tests in clickhouse

- pkg/gofr/datasource/file/sftp/fs.go
- pkg/gofr/datasource/file/sftp/fs_test.go
- pkg/gofr/datasource/file/sftp/go.mod
- pkg/gofr/datasource/file/sftp/go.sum
-   prerequisite to #964 
**Checklist:**
> Fixing linters and tests in sftp file-store

- docs/advanced-guide/injecting-databases-drivers/page.md
- pkg/gofr/datasource/opentsdb/interface.go
- pkg/gofr/datasource/opentsdb/mock_interface.go
- pkg/gofr/datasource/opentsdb/opentsdb.go
- pkg/gofr/datasource/opentsdb/opentsdb_test.go
- pkg/gofr/datasource/opentsdb/preprocess.go
- pkg/gofr/datasource/opentsdb/response.go
-   prerequisite to closing #964 
**Checklist:**
> fixing linters and tests in opentsdb

- pkg/gofr/datasource/dgraph/dgraph.go
- pkg/gofr/datasource/dgraph/dgraph_test.go
- pkg/gofr/datasource/dgraph/interfaces.go
- pkg/gofr/datasource/dgraph/logger.go
-   Resolve linters and failing tests for `Dgraph` datasource.
**Checklist:**
> Fix dgraph linters and tests 

- pkg/gofr/datasource/pubsub/eventhub/eventhub.go
- pkg/gofr/datasource/pubsub/eventhub/eventhub_test.go
- pkg/gofr/datasource/pubsub/eventhub/logger.go
-   Fix linters and tests in `EventHub` datasource.
**Checklist:**
> Fix eventhub linters tests

- pkg/gofr/datasource/pubsub/nats/connection_manager.go
- pkg/gofr/datasource/pubsub/nats/subscription_manager.go
-   Fix `NATS` datasource linters.
**Checklist:**
> fix nats linters

- pkg/gofr/datasource/pubsub/mqtt/mqtt.go
> Revert "change mqtt broker to eclipse broker"

- pkg/gofr/datasource/pubsub/mqtt/default_client.go
- pkg/gofr/datasource/pubsub/mqtt/mqtt.go
- pkg/gofr/datasource/pubsub/mqtt/mqtt_test.go
-   Fix failing test for MQTT package.
> use eclipse broker only for test

- pkg/gofr/migration/migration.go
- pkg/gofr/migration/migration_test.go
-   Closes #1328.
**Checklist:**
> add error log on migrations failure

- docs/advanced-guide/grpc/page.md
- docs/advanced-guide/handling-file/page.md
- docs/advanced-guide/publishing-custom-metrics/page.md
- pkg/gofr/container/container.go
- pkg/gofr/datasource/cassandra/logger.go
- pkg/gofr/datasource/cassandra/mock_logger.go
- pkg/gofr/datasource/clickhouse/logger.go
- pkg/gofr/datasource/clickhouse/mock_logger.go
- pkg/gofr/datasource/kv-store/badger/logger.go
- pkg/gofr/datasource/kv-store/badger/mock_logger.go
- pkg/gofr/datasource/opentsdb/preprocess.go
- pkg/gofr/datasource/opentsdb/response.go
- pkg/gofr/datasource/pubsub/eventhub/eventhub_test.go
- pkg/gofr/datasource/solr/logger.go
- pkg/gofr/datasource/solr/mock_logger.go
- pkg/gofr/logging/logger.go
- pkg/gofr/metrics/register.go
- pkg/gofr/websocket/websocket.go
Fix typo
I used codespell, typos, LanguageTool, cspell but also my own eyes and brain :smile:
> chore: fight against typos

- .github/workflows/go.yml
- README.md
> Revert "Echo merge_coverage in pipeline before uploading the coverage_report"

- pkg/gofr/datasource/mongo/mongo.go
- pkg/gofr/datasource/mongo/mongo_test.go
- linked to #1326 
**Checklist:**
> Fix: MongoDB logs

- docs/advanced-guide/custom-spans-in-tracing/page.md
- docs/advanced-guide/gofr-errors/page.md
- docs/advanced-guide/grpc/page.md
- docs/advanced-guide/publishing-custom-metrics/page.md
- docs/advanced-guide/using-publisher-subscriber/page.md
- docs/advanced-guide/websocket/page.md
- docs/quick-start/add-rest-handlers/page.md
- docs/quick-start/connecting-redis/page.md
- docs/quick-start/observability/page.md
- docs/references/context/page.md
- docs/references/gofr-cli/page.md
- pkg/gofr/metrics/register.go
-   ![image](https://github.com/user-attachments/assets/22a962c0-53c4-478e-a628-9e9a27cc132a)
-   Fix wrong public broker name in MQTT docs.
-   Use consistnet tone in documentation.
> minor correction in documentation's tone

- README.md
- docs/events.json
- adding dates in timeline fixed in the following issue: https://github.com/gofr-dev/website/issues/151
> Adding year in events' timeline

- docs/datasources/arangodb/page.md
- docs/datasources/cassandra/page.md
- docs/datasources/clickhouse/page.md
- docs/datasources/dgraph/page.md
- docs/datasources/getting-started/page.md
- docs/datasources/mongodb/page.md
- docs/datasources/opentsdb/page.md
- docs/datasources/scylladb/page.md
- docs/datasources/solr/page.md
- docs/datasources/summary/page.md
- docs/datasources/surrealdb/page.md
- docs/navigation.js
> Add datasources as a separate section

- docs/Dockerfile
- pkg/gofr/datasource/README.md
-   After the changes in PR #1549 we need to add the newly created directory into dockerfile.
> copy datasources into app/src/docs in dockerfile

- .github/workflows/go.yml
-   Upgrade linter version to `v1.64.0`
- Closes #1608.
**Checklist:**
> En/update linter to v1.64.0

- docs/advanced-guide/circuit-breaker/page.md
-   Enhance [circuit breaker documentation](https://gofr.dev/docs/advanced-guide/circuit-breaker#circuit-breaker-in-http-communication) by properly explaining threshold, interval, retries.
**Checklist:**
> enhance circuit breaker doc

- pkg/gofr/datasource/sql/sql.go
-   Closes #1837 
**Checklist:**
> Fixed otel error in case of Supabase Dialect

- CONTRIBUTING.md
> Adding guidelines related to PR Assignment & triage label in contributing.md

- README.md
- docs/datasources/cockroachdb/page.md
> Added correct docs for cockroachdb

- docs/quick-start/connecting-mysql/page.md
- docs/quick-start/connecting-redis/page.md
- docs/quick-start/introduction/page.md
- docs/quick-start/observability/page.md
This PR fixes a number of mistakes in the Go documentation, focusing on grammar, spelling, and sentence construction.
**Checklist:**
> Fixed Grammatical Mistakes in Go docs

- .qlty/qlty.toml
> Update rules of qlty.toml to match previous code climate

- README.md
Elevate onboarding and accessibility for onboarding users
-   List any breaking changes introduced by this PR. N/A
**Checklist:**
> updates readme contribute

- pkg/gofr/container/container.go
- pkg/gofr/context_test.go
- pkg/gofr/websocket.go
- pkg/gofr/websocket/websocket.go
- pkg/gofr/websocket_test.go
**Key Changes**
**Enhances Contextual WebSocket Connection Retrieval**
- Updates `Container.GetConnectionFromContext` to support retrieving a WebSocket connection directly from the context, not just via a connection ID. This adds a type check for `*websocket.Connection` before falling back to the previous string-based lookup.
**Improves WebSocket Test Robustness and Structure**
- Refactors tests in `context_test.go` and `websocket_test.go` to:
- Use helper functions for WebSocket message handling and testing.
- Improve concurrency safety and test reliability.
- Ensure proper server startup/shutdown and resource cleanup.
- Replace hardcoded waits and direct port usage with a utility for dynamic port allocation.
**Adds Thread-Safe WebSocket Methods**
- Adds `ReadMessage`, `SetReadDeadline`, …
> Fixed websocket implementation & tests

- docs/advanced-guide/overriding-default/page.md
Description:
-   This is regarding HTTP methods should be redirected, and what status codes are set when such redirects occur.
-   This PR is related to this issue: https://github.com/gofr-dev/gofr/issues/2160
-   Please find the changes on this page: https://gofr.dev/docs/advanced-guide/overriding-default
> Update documentation for HTTP Redirect (revert changes of go.work.sum)

- .github/workflows/go.yml
-   Change kafka image from **bitnami/kafka** to **bitnamilegacy/kafka**.
**Checklist:**
> update kafka image from bitnami/kafka to  bitnamilegacy/kafka

- docs/references/context/page.md
- Added documentation for the new `GetAuthInfo()` method in the GoFr Context section.
- This update explains how developers can access authentication details (JWT claims, username, and API key) from the context and specifies which GoFr middleware must be enabled for each method.
- Fixes: Add documentation for GetAuthInfo feature https://github.com/gofr-dev/gofr/issues/2346 .  
**Motivation:**
- Improves clarity for developers by demonstrating how to retrieve authentication information populated by GoFr’s authentication middlewares (`EnableOAuth`, `EnableBasicAuthWithValidator`, and `EnableAPIKeyAuthWithValidator`).
**Expected Benefit:**
- Provides a straightforward reference for developers using authentication features in GoFr, reducing confusion and improving usability …
> Updated the documentation
